package com.snapdeal.payments.view.commons.enums;


public enum ExceptionType {

	JSON_PARSE_EXCEPTION,
	JSON_MAPPING_EXCEPTION,
	IO_EXCEPTION,
	NULL_POINTER_EXCEPTION,
	MERCHANT_ON_BOARDING,
	MERCHANT_NAME_NOT_FOUND,
	PAYABLE_EXCEPTION,
	TSM_EXCEPTION,
	CLASS_CAST_EXCEPTION,
	UNKNOWN_EXCEPTION,
	SQL_EXCEPTION,
	DATA_INTEGRITY_EXCEPTION,
	SDMONEY_EXCEPTION
}
