package com.snapdeal.ums.core.entity;

// Generated 29 Jun, 2012 10:08:39 AM by Hibernate Tools 3.2.4.GA

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.snapdeal.base.utils.DateUtils;

/**
 * City generated by hbm2java
 */
@Entity
@Table(name = "email_city_esp_mapping", catalog = "ums")
public class EmailBulkEspCityMapping implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 7786688999999991701L;
    private Integer           		id;
    private Integer           			cityId;
    private EmailServiceProvider    esp;
    private Date                   updated;

    public EmailBulkEspCityMapping() {
        this.updated = DateUtils.getCurrentTime();
    }

    public EmailBulkEspCityMapping(EmailServiceProvider esp, Integer cityId) {
        this.esp = esp;
        this.cityId = cityId;
        this.updated = DateUtils.getCurrentTime();
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "esp_id", nullable = false)
    public EmailServiceProvider getEsp() {
        return this.esp;
    }

    public void setEsp(EmailServiceProvider esp) {
        this.esp = esp;
    }

    @Column(name = "city_id", nullable = false)
    public Integer getCityId() {
        return cityId;
    }

    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

 

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated", nullable = false, length = 19, updatable = false, insertable = false)
    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }
    
}