package com.snapdeal.ums.core.entity;

// Generated May 18, 2011 4:26:32 PM by Hibernate Tools 3.3.0.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.snapdeal.base.utils.DateUtils;

/**
 * EmailMobileAssociation generated by hbm2java
 */
@Entity
@Table(name = "email_mobile_association", catalog = "ums", uniqueConstraints = @UniqueConstraint(columnNames = { "email", "mobile" }))
public class EmailMobileAssociation implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 2455619836945806937L;
    private Integer           id;
    private String            email;
    private String            mobile;
    private boolean           verified;
    private Date              created;
    
    public EmailMobileAssociation() {
    }
    
    public EmailMobileAssociation(String email, String mobile, boolean verified,Date created) {
        this.email = email;
        this.mobile = mobile;
        this.verified = verified;
        this.created = created;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "email", nullable = false, length = 100)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "mobile", nullable = false, length = 10)
    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    @Column(name = "verified", nullable = false)
    public boolean isVerified() {
        return this.verified;
    }

    public void setVerified(boolean verified) {
        this.verified = verified;
    }

   
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

}
