package com.snapdeal.ums.core.entity;


import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", catalog = "ums")
public class Role implements java.io.Serializable {

    public enum RoleDef {


        UNVERIFIED("unverified"), REGISTERED("registered"), ADMIN("admin"), BUSINESS_DEVELOPMENT("bd"), CONTENT_MANAGER("content"), SUPER("super"), VENDOR("vendor"), AFFILIATE(
                "affiliate"), CCMANAGER("ccmanager"), MARKETING("marketing"), GETAWAYS_BD("getaways-bd"), PRODUCT("product"), CAMPAIGN_MGR("campaignmgr"), CC_EXECUTIVE(
                "ccexecutive"), FINANCE("finance"), SHIPPROVIDER("shipprovider"), MIS("mis"), AUDIT("audit"), SEO("seo"), CONTENT_MGR("ContentMgr"), AM("am"), AM_CHEIF("amchief",
                AM), DESIGN("design"), DESIGN_CHEIF("designchief", DESIGN), CONTENT("content"), CONTENT_CHEIF("contentchief", CONTENT), QA("qa"), QA_CHEIF("qachief", QA), HR("hr"), CS_ADMIN(
                "csadmin"), LOGISTICS("logistics"), CANCELLATION_APPROVER_LOGISTICS("canAppLogistics", LOGISTICS), PRODUCT_SOURCING("productsourcing"), CATEGORY_ADMIN(
                "categoryAdmin"), STOREFRONTSUPERADMIN("storefrontSuperAdmin"), ORDERFULFILLMENT("orderfulfillment"), CCEXECUTIVE_OUTGOING("ccexecutiveoutgoing"),
                PCEXECUTIVE("pcexecutive"),PCMANAGER("pcmanager"), CODVERIFICATION("codverification"), MARKETINGSFADMIN("marketingsfadmin"), CATEGORY("category"),
                OMS_CFR_ADMIN("OMSCFRAdmin"),OMS_VRA_ADMIN("OMSVRAAdmin"),OMS_CASHBACK_ADMIN("OMSCashbackAdmin"),OMS_BULKPARTIALCANCELLATION_ADMIN("OMSBulkPartialCancellationAdmin"),
                OMS_CODVERIFICATION_ADMIN("OMSCODVerificationAdmin"),OMS_RESTRICTEDCANCELLATION_ADMIN("OMSRestrictedCancellationAdmin"),OMS_CC_ADMIN("OMSCCAdmin"),
                OMS_ALTERNATE_ADMIN("OMSAlternateAdmin"),OMS_TASK_ADMIN("OMSTaskAdmin"),OMS_RESTRICTEDPAYMENTMODE_ADMIN("OMSRestrictedPaymentModeAdmin"),
                OMS_NEFT_ADMIN("OMSNeftAdmin"),OMS_TEMPLATE_ADMIN("OMSTemplateAdmin"),OMS_ADMIN("OMSAdmin"),OMS_RETRIGGER_ADMIN("OMSRetriggerAdmin");


        private String code;
        private RoleDef subRoleDef = null;

        private RoleDef(String code) {
            this.code = code;
        }


        private RoleDef(String code,RoleDef subRole) {
            this.code = code;
            subRoleDef = subRole;
        }

        public String code() {
            return this.code;
        }
        
        public RoleDef getSubordinateRole() {
            if (subRoleDef != null)
                return subRoleDef;
            else
                return null;
        }

    }

    /**
     *
     */
    private static final long serialVersionUID = 5709022770089587159L;

    private int               id;
    private String            code;
    private String            description;

    public Role() {
    }

    public Role(String code) {
        this.code = code;
    }
    
    public Role(String code,String description) {
        this.code = code;
        this.description = description;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    @Column(name = "code", length = 11)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code.toLowerCase();
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name = "description")
    public String getDescription() {
        return description;
    }

    @Override
    public String toString() {
        return "Role [code=" + code + "]";
    }

    /* (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((code == null) ? 0 : code.hashCode());
        return result;
    }

    /* (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        Role other = (Role) obj;
        if (code == null) {
            if (other.code != null)
                return false;
        } else if (!code.equals(other.code))
            return false;
        return true;
    }
    
}
