package com.snapdeal.ums.core.entity;

// Generated 16 Aug, 2010 10:08:39 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

import com.snapdeal.ums.core.utils.QueryNames;

/**
 * SnapdealProperty generated by hbm2java
 */
@Entity
@Table(name = "ums_property", catalog = "ums")
@NamedQueries({ @NamedQuery(name = QueryNames.GET_ALL_PROPERTIES, query = "from UMSProperty") })
public class UMSProperty implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = -6507176103210740800L;
    private String            name;
    private String            value;

    public UMSProperty() {
    }

    public UMSProperty(String name, String value) {
        this.name = name;
        this.value = value;
    }

    @Id
    @Column(name = "name", unique = true, nullable = false, length = 48)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "value", nullable = false, length = 256)
    public String getValue() {
        return this.value;
    }

    public void setValue(String value) {
        this.value = value;
    }

}
