package com.snapdeal.ums.core.entity;

// Generated 16 Aug, 2010 10:08:39 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.snapdeal.ums.core.utils.QueryNames;

/**
 * UserReferralTracking generated by hbm2java
 */
@Entity
@Table(name = "user_referral_tracking", catalog = "ums")
@NamedQueries({ @NamedQuery(name = QueryNames.GET_USER_REFERRAL_TRACKING, query = "from UserReferralTracking where user=:user and referralChannel = :referralChannel") })
public class UserReferralTracking implements java.io.Serializable {

    public static final String REFERRAL_CHANNEL_EMAIL    = "email";
    public static final String REFERRAL_CHANNEL_FACEBOOK = "facebook";
    public static final String REFERRAL_CHANNEL_TWITTER  = "twitter";
    public static final String REFERRAL_CHANNEL_OTHERS   = "others";

    /**
     * 
     */
    private static final long  serialVersionUID          = 5759035414912648509L;
    private Integer            id;
    private User               user;
    private String             referralChannel;
    private int                sentCount;
    private int                clickCount;
    private int                conversionCount;
    private Date               created;

    public UserReferralTracking() {
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created", nullable = false, length = 19)
    public Date getCreated() {
        return this.created;
    }

    public void setCreated(Date created) {
        this.created = created;
    }

    @Column(name = "referral_channel")
    public String getReferralChannel() {
        return referralChannel;
    }

    public void setReferralChannel(String referralChannel) {
        this.referralChannel = referralChannel;
    }

    @Column(name = "sent_count")
    public int getSentCount() {
        return sentCount;
    }

    public void setSentCount(int sentCount) {
        this.sentCount = sentCount;
    }

    @Column(name = "click_count")
    public int getClickCount() {
        return clickCount;
    }

    public void setClickCount(int clickCount) {
        this.clickCount = clickCount;
    }

    @Column(name = "conversion_count")
    public int getConversionCount() {
        return conversionCount;
    }

    public void setConversionCount(int conversionCount) {
        this.conversionCount = conversionCount;
    }

}
