package com.snapdeal.ums.core.entity;

// Generated 16 Aug, 2010 10:08:39 PM by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.snapdeal.base.utils.DateUtils;

/**
 * UserOpenidMapping generated by hbm2java
 */
@Entity
@Table(name = "user_openid_mapping", catalog = "ums")
public class UserOpenidMapping implements java.io.Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 2495040743879611073L;
    private Integer           id;
    private User              user;
    private String            identifier;
    private String            provider;
    private Date              updated;
    
    public UserOpenidMapping() {
      this.updated  = DateUtils.getCurrentTime(); 
    }

    public UserOpenidMapping(User user, String identifier, String provider) {
        this.user = user;
        this.identifier = identifier;
        this.provider = provider;
        this.updated = DateUtils.getCurrentTime();
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "identifier", nullable = false)
    public String getIdentifier() {
        return this.identifier;
    }

    public void setIdentifier(String identifier) {
        this.identifier = identifier;
    }

    @Column(name = "provider", nullable = false, length = 48)
    public String getProvider() {
        return this.provider;
    }

    public void setProvider(String provider) {
        this.provider = provider;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated", nullable = false, length = 19)
    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }
}
