package com.snapdeal.ums.core.entity;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.snapdeal.base.utils.DateUtils;

/**
 * ZendeskUser generated by kuldeep
 */

@Entity
@Table(name = "zendesk_user", catalog = "ums")
public class ZendeskUser implements Serializable {

    /**
     * 
     */
    private static final long serialVersionUID = 5420891110726472238L;
    private Integer           id;
    private User              user;
    private String            password;
    private Date              updated;

    public ZendeskUser(){
        this.updated = DateUtils.getCurrentTime();;
    }
    
    
    public ZendeskUser(User user, String password) {
        super();
        this.user = user;
        this.password = password;
        this.updated = DateUtils.getCurrentTime();
    }


    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    @Column(name = "password", nullable = false)
    public String getPassword() {
        return password;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated", nullable = false, length = 19, updatable = false, insertable = false)
    public Date getUpdated() {
        return updated;
    }

    public void setUpdated(Date updated) {
        this.updated = updated;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return user;
    }
}
