package com.snapdeal.opspanel.promotion.enums;

public enum FileState {

	FILE_UPLOAD_SCHEDULED,
	FILE_UPLOAD_TO_S3_COMPLETED,
	FILE_FORMAT_INCORRECT,
	NO_ENTRY_FOUND_IN_FILE,
	FILE_SIZE_INVALID,
	DATA_NOT_IN_CORRECT_FORMAT,
	FILE_RESULT_UPLOAD_FAIL,
	FILE_DOWNLOAD__FROM_S3_FAIL,
	INSUFFICIENT_BALANCE_IN_CORP_ACCOUNT,
	SCHEDULED_EXECUTION,
	EXECUTION_COMPLETE,
	EXECUTION_FAILED, FILE_UPLOAD_TO_S3_FAIL,
	FILE_READ_FAIL,
	CAMPAIGN_KEY_ALREADY_USED,
	GO_GREEN_FOR_CAMPAIGN_KEY

}
