/**
 * 
 */
package com.snapdeal.ims.enums;


public enum State {

	SD_ACCOUNT_EXISTS_AND_DISABLED, 
	SD_ACCOUNT_EXISTS_AND_ENABLED, 
	SD_ACCOUNT_NOT_EXISTS, 
	SD_ACCOUNT_MIGRATED, 
	FC_ACCOUNT_EXISTS_AND_DISABLED, 
	FC_ACCOUNT_EXISTS_AND_ENABLED, 
	FC_ACCOUNT_NOT_EXISTS, 
	FC_ACCOUNT_MIGRATED, 
	OC_ACCOUNT_EXISTS, 
	OC_ACCOUNT_EXISTS_AND_DISABLED, 
	OC_ACCOUNT_NOT_EXISTS, 
	SD_FC_ACCOUNT_EXISTS_AND_ENABLED, 
	SD_ENABLED_FC_DISABLED_EXISTS, 
	SD_DISABLED_FC_ENABLED_EXISTS, 
	SD_FC_ACCOUNT_EXISTS_AND_DISABLED;
}
