ALTER TABLE ims.upgrade
CHANGE COLUMN upgrade_source upgrade_source ENUM('SIGN_IN','SIGN_UP','ORDER_FLOW','THANK_YOU','MY_ACCOUNT','RETURN­_ORDER','OTHERS','ONECHECK_SOCIAL_SIGNUP') NOT NULL DEFAULT 'OTHERS';
