ALTER TABLE activity_log 
ADD COLUMN server_ip_address VARCHAR(128) NULL DEFAULT NULL ;
ADD COLUMN server_ip_address VARCHAR(128) NULL DEFAULT NULL ;

ALTER TABLE activity_log 
ADD COLUMN server_ip_address VARCHAR(128) NULL DEFAULT NULL ;
