CREATE TABLE `ims_apis` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `alias` varchar(45) DEFAULT NULL,
  `api_method` varchar(45) NOT NULL,
  `api_uri` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Unique API` (`api_method`,`api_uri`)
);

INSERT INTO `ims_apis` VALUES 
(null, 'isEmailExist','GET','/api/v1/identity/users/exists/email/{emailId}'),
(null, 'updateUserByToken','PUT','/api/v1/identity/users/token/{token}'),
(null, 'updateMobileNumber','PUT','/api/v1/identity/users/mobile'),
(null, 'createUserWithMobile','POST','/api/v1/identity/users/mobile/generate'),
(null, 'verifyUser','GET','/api/v1/identity/users/guest/verify/{code}'),
(null, 'isUserExist','GET','/api/v1/identity/users/exists/user/{userId}'),
(null, 'verifySocialUserWithMobile','POST','/api/v1/identity/users/social/mobile/verify'),
(null, 'getUserByEmail','GET','/api/v1/identity/users/email/{email}'),
(null, 'getUserByMobile','GET','/api/v1/identity/users/mobile/{mobileNumber}'),
(null, 'createOrLoginSocialUser','POST','/api/v1/identity/users/social'),
(null, 'createGuestUserWithEmail','POST','/api/v1/identity/users/guest/create'),
(null, 'isVerifiedMobileExist','GET','/api/v1/identity/users/exists/mobile/{mobileNumber}'),
(null, 'updateUserById','PUT','/api/v1/identity/users/{userId}'),
(null, 'createSocialUserWithMobile','POST','/api/v1/identity/users/social/mobile'),
(null, 'verifyUserWithMobile','POST','/api/v1/identity/users/mobile/verify'),
(null, 'getUserByToken','GET','/api/v1/identity/users/token/{token}'),
(null, 'createUserWithEmail','POST','/api/v1/identity/users/email'),
(null, 'createUserWithEmailAndMobile','POST','/api/v1/identity/users/email/mobile'),
(null, 'configureUserState','PUT','/api/v1/identity/users/enable'),
(null, 'getUser','GET','/api/v1/identity/users/{userId}'),
(null, 'userUpgradeStatus','POST','/api/v1/identity/users/upgrade/status'),
(null, 'verifyUpgradeUser','POST','/api/v1/identity/users/upgrade/verify'),
(null, 'upgradeUser','POST','/api/v1/identity/users/upgrade'),
(null, 'verifyOTP','POST','/api/v1/identity/otp/verify'),
(null, 'reSendOTP','POST','/api/v1/identity/otp/resend'),
(null, 'isValidOTP','GET','/api/v1/identity/otp/valid/{otpId}/{otp}'),
(null, 'generateOTP','POST','/api/v1/identity/otp/send'),
(null, 'getConfigurationDetails','GET','/api/v1/identity/configurationDetails/{configuration}'),
(null, 'verifyUniqueMobile','POST','/api/v1/identity/mobile/verify'),
(null, 'signInWithToken','POST','/api/v1/identity/signin/token'),
(null, 'forgotPassword','POST','/api/v1/identity/users/forgotpassword/otp'),
(null, 'sendForgotPasswordLink','POST','/api/v1/identity/forgotpassword'),
(null, 'changePasswordWithLogin','PUT','/api/v1/identity/users/changepasswordwithlogin'),
(null, 'signout','POST','/api/v1/identity/signout'),
(null, 'getTransferToken','PUT','/api/v1/identity/token/transfer'),
(null, 'resetPassword','PUT','/api/v1/identity/users/forgotpassword/otp'),
(null, 'signInWithTransferToken','POST','/api/v1/identity/signin/token/transfer'),
(null, 'resetPasswordAndLogin','PUT','/api/v1/identity/users/forgotpassword/otpandlogin'),
(null, 'changePassword','PUT','/api/v1/identity/users/changepassword'),
(null, 'verifyUserAndResetPassword','POST','/api/v1/identity/forgetpassword/verify'),
(null, 'signIn','POST','/api/v1/identity/signin/users'),
(null, 'WhitelistEmail','POST','/api/v1/identity/users/whitelist/email'),
(null, 'removeBlacklistEntity','DELETE','/api/v1/identity/users/blacklist/entity/{entityType}/{entity}'),
(null, 'addBlacklistEntity','POST','/api/v1/identity/users/blacklist/entity');

