DROP TABLE IF EXISTS `user`;
CREATE TABLE `user` (
  `user_id` varchar(128) NOT NULL,
  `sd_user_id` int(11) DEFAULT NULL,
  `fc_user_id` int(11) DEFAULT NULL,
  `sd_fc_user_id` int(11) NOT NULL AUTO_INCREMENT,
  `originating_src` enum('FREECHARGE','SNAPDEAL','ONECHECK') NOT NULL,
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `email` varchar(255) NOT NULL,
  `password` varchar(255) DEFAULT NULL,
  `is_user_set_password` tinyint(1) DEFAULT '0',
  `mobile_number` varchar(20) DEFAULT NULL,
  `status` enum('NOT_VERIFIED','GUEST','REGISTERED','TEMP') NOT NULL DEFAULT 'NOT_VERIFIED',
  `is_google_user` tinyint(1) NOT NULL DEFAULT '0',
  `is_facebook_user` tinyint(1) NOT NULL DEFAULT '0',
  `is_email_verified` tinyint(1) NOT NULL DEFAULT '0',
  `is_mobile_verified` tinyint(1) NOT NULL DEFAULT '0',
  `first_name` varchar(128) DEFAULT NULL,
  `last_name` varchar(128) DEFAULT NULL,
  `middle_name` varchar(128) DEFAULT NULL,
  `display_name` varchar(128) DEFAULT NULL,
  `gender` enum('m','f','o') DEFAULT NULL,
  `dob` date DEFAULT NULL,
  `language_pref` enum('HINDI','ENGLISH') NOT NULL DEFAULT 'ENGLISH',
  `purpose` varchar(255) DEFAULT NULL,
  `created_time` datetime,
  `updated_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `sd_fc_user_id_UNIQUE` (`sd_fc_user_id`),
  KEY `mobile` (`mobile_number`)
) AUTO_INCREMENT = 130000000;
