package com.snapdeal.payments.view.request.commons.enums;

import lombok.Getter;

public enum RVTxnState {
	
	MONEY_REQUESTED("REQUEST_MONEY","MONEY_REQUESTED"),
	MONEY_REQUESTED_APPROVED("MONEY_REQUEST_APPROVED","MONEY_REQUESTED_APPROVED"),
	MONEY_REQUESTED_FAILED("REQUEST_MONEY_FAILED","MONEY_REQUESTED_FAILED"),
	MONEY_REQUESTED_REJECTED("REQUEST_MONEY_REJECTED","MONEY_REQUESTED_REJECTED"),
	MONEY_REQUESTED_CANCELLED("REQUEST_MONEY_CANCELLED","MONEY_REQUESTED_CANCELLED"),
	MONEY_REQUESTED_EXPIRED("REQUEST_MONEY_EXPIRED","MONEY_REQUESTED_EXPIRED"),
	MONEY_RECIEVED("MONEY_RECIEVED","MONEY_SENT"),
	
	SEND_MONEY_REQUEST("SEND_MONEY_REQUEST",""),
	SEND_MONEY_REQUEST_FAILED("SEND_MONEY_REQUEST_FAILED",""),
	SEND_MONEY_REQUEST_MONEY_PARKED("SEND_MONEY_REQUEST_MONEY_PARKED","MONEY_RECIEVED"),
	MONEY_SENT("MONEY_SENT","MONEY_RECIEVED");
	

	
	@Getter
	private String sourceStatus,destStatus;
	private RVTxnState(String source,String dest) {
		this.sourceStatus=source;
		this.destStatus=dest;
	}
	
	

}
